// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PetGest.Api.Data;

#nullable disable

namespace PetGest.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261003210743_V0Schema")]
    partial class V0Schema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PetGest.Api.Data.Entities.Petshop", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.HasKey("Id")
                        .HasName("petshops_pkey");

                    b.ToTable("petshops", null, t =>
                        {
                            t.HasCheckConstraint("petshops_email_check", "length(btrim(email)) > 0");

                            t.HasCheckConstraint("petshops_name_check", "length(btrim(name)) > 0");
                        });
                });

            modelBuilder.Entity("PetGest.Api.Data.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Ean")
                        .HasColumnType("text")
                        .HasColumnName("ean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("PetshopId")
                        .HasColumnType("uuid")
                        .HasColumnName("petshop_id");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("price");

                    b.Property<string>("Source")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("manual")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id")
                        .HasName("products_pkey");

                    b.HasIndex("PetshopId", "Ean")
                        .IsUnique()
                        .HasDatabaseName("products_petshop_ean_key")
                        .HasFilter("ean IS NOT NULL");

                    b.ToTable("products", null, t =>
                        {
                            t.HasCheckConstraint("products_category_check", "length(btrim(category)) > 0");

                            t.HasCheckConstraint("products_ean_check", "ean is null or ean ~ '^[0-9]{8,14}$'");

                            t.HasCheckConstraint("products_name_check", "length(btrim(name)) > 0");

                            t.HasCheckConstraint("products_price_check", "price >= 0");

                            t.HasCheckConstraint("products_source_check", "source in ('barcode', 'manual')");
                        });
                });

            modelBuilder.Entity("PetGest.Api.Data.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("PetshopId")
                        .HasColumnType("uuid")
                        .HasColumnName("petshop_id");

                    b.HasKey("Id")
                        .HasName("profiles_pkey");

                    b.HasIndex("PetshopId")
                        .HasDatabaseName("profiles_petshop_id_idx");

                    b.ToTable("profiles", (string)null);
                });

            modelBuilder.Entity("PetGest.Api.Data.Entities.Product", b =>
                {
                    b.HasOne("PetGest.Api.Data.Entities.Petshop", null)
                        .WithMany()
                        .HasForeignKey("PetshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("products_petshop_id_fkey");
                });

            modelBuilder.Entity("PetGest.Api.Data.Entities.Profile", b =>
                {
                    b.HasOne("PetGest.Api.Data.Entities.Petshop", null)
                        .WithMany()
                        .HasForeignKey("PetshopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("profiles_petshop_id_fkey");
                });
#pragma warning restore 612, 618
        }
    }
}
