-- T-18, passo 5: migrations depois da importacao das contas: ProfilesUserFk (FK de
-- profiles.id para identity.users) e todas as seguintes (gerado pelo EF, idempotente).
-- Se houver migration nova, REGERE antes da virada (o T18RehearsalTests falha se este
-- arquivo ficar para tras). Em backend/:
--   dotnet ef migrations script 20261003221054_IdentitySchema --idempotent --project Api -o deploy/t18/05-migrations-depois-da-importacao.sql

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261003221121_ProfilesUserFk') THEN
    alter table public.profiles drop constraint if exists profiles_id_fkey;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261003221121_ProfilesUserFk') THEN
    ALTER TABLE profiles ADD CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES identity.users (id) ON DELETE CASCADE;
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261003221121_ProfilesUserFk') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20261003221121_ProfilesUserFk', '10.0.12');
    END IF;
END $EF$;
COMMIT;

START TRANSACTION;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261007030626_DataProtectionKeys') THEN
    CREATE TABLE identity.data_protection_keys (
        id integer GENERATED BY DEFAULT AS IDENTITY,
        friendly_name text,
        xml text,
        CONSTRAINT data_protection_keys_pkey PRIMARY KEY (id)
    );
    END IF;
END $EF$;

DO $EF$
BEGIN
    IF NOT EXISTS(SELECT 1 FROM "__EFMigrationsHistory" WHERE "migration_id" = '20261007030626_DataProtectionKeys') THEN
    INSERT INTO "__EFMigrationsHistory" (migration_id, product_version)
    VALUES ('20261007030626_DataProtectionKeys', '10.0.12');
    END IF;
END $EF$;
COMMIT;

